config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  devise_for :users

  resources :users, only: [:index, :show] 
    resources :friendships
    # , only: [:create,:destory,:index,:show] 
  resources :posts, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: :User
  validates_uniqueness_of :user_id, scope: %i[friend_id]
  validates_uniqueness_of :friend_id, scope: %i[user_id]

  # scope :friendlist, -> { where('status = ?', true) }
  # scope :waiting, -> { where('status = ?', false) }

  after_update :create_friend

  def await(current_user, _user)
    x = current_user.requests_sent
    x1 = current_user.requests_received

    x2 = x + x1

    x2.empty? ? nil : x2
  end

  def friendss(current_user, _user)
    # y = Friendship.where('friend_id = ?', current_user.id).and(Friendship.where('user_id = ?',
    #                                                                             user.id)).friendlist

    # y1 = Friendship.where('friend_id = ?', user.id).and(Friendship.where('user_id = ?', current_user.id)).friendlist

    # y2 = y + y1

    y2 = current_user.friendships

    y2.empty? ? nil : y2
  end

  def pendingreq(currentuser)
    @awaitng = currentuser.requests_received

    # Friendship.where('friend_id = ?', currentuser.id).waiting
  end

  private

  def create_friend
    Friendship.create(status: true, friend_id: user_id, user_id: friend_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(params_new)
    if @friendship.save
      redirect_to root_path, notice: 'Friend Request Sent'
    else
      redirect_to root_path, alert: 'Request Already sent'
    end
  end

  def new; end

  def show
    @awaitng = current_user.requests_received
  end

  def destroy
    delete = Friendship.find_by_id(delete_params[:id])
    if delete.destroy
      redirect_to friendship_path(current_user.id), method: :get, notice: 'Request Declined'
    else
      redirect_to friendship_path(current_user.id), method: :get, notice: 'Failed to decline. Please try again'
    end
  end

  def update
    record = Friendship.find_by_id(update_params[:id])
    if record.update(update_params)
      redirect_to friendship_path(current_user.id), method: :get, notice: 'Request Accepted'
    else
      redirect_to friendship_path(current_user.id), method: :get, notice: 'Failed to Accept. Please try again'
    end
  end

  private

  def params_new
    params.permit(:friend_id)
  end

  def delete_params
    params.permit(:id)
  end

  def update_params
    params.permit(:id, :status)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_awaiting.html.erb
<h4 class="btn btn-warning">Awaiting Confirmation</h4>

app/views/friendships/_friends.html.erb
<h4 class="btn btn-primary">Friend</h4>

app/views/friendships/_onshowrequest.html.erb
        <%= link_to 'Send Request', friendships_path(friend_id: user.id), method: :create,  class: 'profile-link' %>

app/views/friendships/show.html.erb
<h2>Requests</h2>
<table class="table container table-sm ">
    <thead class='thead-dark'>
        <tr>
            <th>Name</th>
            <th>Accept</th>
            <th>Decline</th>
        </tr>
    </thead>

    <tbody>
        <% @awaitng.each do |f| %>
        <tr>

            <td><%= (User.find_by_id(f.user_id)).name %> </td>


            <td>
                <button class="btn btn-success">
                    <%= link_to "Accept",friendship_path(f.id,status:true),method: :patch , style: "text-decoration: none; color: white" %>
                </button>
            </td>


            <td>
                <button class="btn btn-danger">
                    <%= link_to "Decline",friendship_path(f.id),method: :delete, style: "text-decoration: none; color: white" %>
                </button>
            </td>

        </tr>

        <%end%>
    </tbody>
</table>