config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  devise_for :users

  resources :users, only: [:index, :show] 
    resources :friendships
    # , only: [:create,:destory,:index,:show] 
  resources :posts, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { maximum: 1000,
                                                too_long: '1000 characters in post is the maximum allowed.' }

  belongs_to :user

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.new
    timeline_posts
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      timeline_posts
      render :index, alert: 'Post was not created.'
    end
  end

  private

  def timeline_posts
    @timeline_posts ||= Post.all.ordered_by_most_recent.includes(:user)
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/post_helper.rb
module PostHelper
  def display_errors(post)
    return unless post.errors.full_messages.any?

    content_tag :p, "Post could not be saved. #{post.errors.full_messages.join('. ')}", class: 'errors'
  end

  def posthelper(currentuser, post, friendobject)
    return unless currentuser == post.user or friendobject.friendss(currentuser, post.user)

    render partial: 'posts/friendspost', locals: { post: post }
  end
end

app/views/posts/_friendspost.html.erb
   <div>
       <div class='post-attribution'>
           <%= link_to post.user.name, user_path(post.user), class: 'post-author' %>
       </div>
       <div class='post-liking'>
           <span class='post-date'> <%= post.created_at.strftime("%Y/%m/%d") %> </span>
           <%= like_or_dislike_btn(post) %>
       </div>
   </div>
   <p class="post-content">
       <%= post.content %>
   </p>


   <div class='post-comments-section'>
       <%= render partial: 'comments/comment', collection: post.comments %>

       <%= form_for(post.comments.new, url: post_comments_path(post)) do |form| %>
       <%= form.text_field :content, id: :comment_content, class: 'form-control', placeholder: 'Add new Comment' %>
       <%= form.submit 'Comment', class: 'btn btn-secondary' %>
       <% end %>
   </div>

app/views/posts/_post.html.erb
<li class="post">
    <% friendobject = Friendship.new %>
    <%=posthelper(current_user,post,friendobject)%>
</li>

app/views/posts/index.html.erb
<%= form_for(@post) do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content, id: :post_content, class: 'form-control', placeholder: 'Add New Post' %>
  <%= display_errors(@post) %>
  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

<article class="timeline">
  <h3>
    Recent posts
  </h3>
  <ul class="posts">
    <%= render @timeline_posts %>
  </ul>
</article>