config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  devise_for :users

  resources :users, only: [:index, :show] 
    resources :friendships
    # , only: [:create,:destory,:index,:show] 
  resources :posts, only: [:index, :create] do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alertp.html.erb
 <div class="alert">
     <p> <%= alert %> </p>
 </div>

app/views/layouts/_currentpartial.html.erb
 <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>

app/views/layouts/_devise.html.erb
  <div class="field">
      <%= variable1.check_box :remember_me %>
      <%= variable1.label :remember_me %>
  </div>

app/views/layouts/_noncurrentpartial.html.erb
        <%= link_to 'Sign in', user_session_path %>

app/views/layouts/_noticep.html.erb
   <div class="notice">
       <p> <%= notice %> </p>
   </div>

app/views/layouts/_showinnav.html.erb
                <%= link_to 'Friend Requests', friendship_path(current_user.id) %>

app/views/layouts/_showinnavbut.html.erb
<button class="btn btn-primary  btn-sm">
    <%= link_to "Friend Requests #{count.count}", friendship_path(current_user.id) , style: "text-decoration: none; color: white; word-wrap:break-word;width:200px" %>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>RorSocialScaffold</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <nav class="nav">
        <%= link_to 'Stay in touch', root_path %>
        <div class="menu">
            <div class="menu-item">
                <%= menu_link_to 'Timeline', posts_path %>
            </div>
            <div class="menu-item">
                <%= checkusercurrent%>
            </div>

            <div class="menu-item">
                <%= menu_link_to 'All users', users_path %>
            </div>
        </div>
        <%=current_user1%>

    </nav>

    <%=notice1%>

    <%=alert1%>

    <main class="main">
        <%= yield %>
    </main>
</body>

</html>